In [1]:
import pandas as pd
from NBEATS import NeuralBeats
from sklearn.metrics import mean_squared_error
from math import sqrt

data = pd.read_csv('https://raw.githubusercontent.com/castellanoj/database/main/ipca.csv', encoding='ISO-8859-1')
data = data.values[0:300]
print(data)

print()
data36 = data[300-36:300]
print(data36)
print()

[[ 1.34]
 [ 1.03]
 [ 0.35]
 [ 1.26]
 [ 1.22]
 [ 1.19]
 [ 1.11]
 [ 0.44]
 [ 0.15]
 [ 0.3 ]
 [ 0.32]
 [ 0.47]
 [ 1.18]
 [ 0.5 ]
 [ 0.51]
 [ 0.88]
 [ 0.41]
 [ 0.54]
 [ 0.22]
 [-0.02]
 [ 0.06]
 [ 0.23]
 [ 0.17]
 [ 0.43]
 [ 0.71]
 [ 0.46]
 [ 0.34]
 [ 0.24]
 [ 0.5 ]
 [ 0.02]
 [-0.12]
 [-0.51]
 [-0.22]
 [ 0.02]
 [-0.12]
 [ 0.33]
 [ 0.7 ]
 [ 1.05]
 [ 1.1 ]
 [ 0.56]
 [ 0.3 ]
 [ 0.19]
 [ 1.09]
 [ 0.56]
 [ 0.31]
 [ 1.19]
 [ 0.95]
 [ 0.6 ]
 [ 0.62]
 [ 0.13]
 [ 0.22]
 [ 0.42]
 [ 0.01]
 [ 0.23]
 [ 1.61]
 [ 1.31]
 [ 0.23]
 [ 0.14]
 [ 0.32]
 [ 0.59]
 [ 0.57]
 [ 0.46]
 [ 0.38]
 [ 0.58]
 [ 0.41]
 [ 0.52]
 [ 1.33]
 [ 0.7 ]
 [ 0.28]
 [ 0.83]
 [ 0.71]
 [ 0.65]
 [ 0.52]
 [ 0.36]
 [ 0.6 ]
 [ 0.8 ]
 [ 0.21]
 [ 0.42]
 [ 1.19]
 [ 0.65]
 [ 0.72]
 [ 1.31]
 [ 3.02]
 [ 2.1 ]
 [ 2.25]
 [ 1.57]
 [ 1.23]
 [ 0.97]
 [ 0.61]
 [-0.15]
 [ 0.2 ]
 [ 0.34]
 [ 0.78]
 [ 0.29]
 [ 0.34]
 [ 0.52]
 [ 0.76]
 [ 0.61]
 [ 0.47]
 [ 0.37]
 [ 0.51]
 [ 0.71]
 [ 0.91]
 [ 0.69]
 [ 0.33]
 [ 0.44]
 [ 0.69]
 [ 0.86]
 [ 0.58]
 [ 0.59]
 [ 0.61]
 

In [2]:
model = NeuralBeats(data=data, forecast_length=12, hidden_layer_units=264 )
model.fit(plot=False, verbose=False, epoch=50)

| N-Beats
| --  Stack Generic (#0) (share_weights_in_stack=False)
     | -- GenericBlock(units=1, thetas_dim=4, backcast_length=36, forecast_length=12, share_thetas=False) at @140604789377008
     | -- GenericBlock(units=1, thetas_dim=4, backcast_length=36, forecast_length=12, share_thetas=False) at @140607838488656
     | -- GenericBlock(units=1, thetas_dim=4, backcast_length=36, forecast_length=12, share_thetas=False) at @140607838165168
| --  Stack Generic (#1) (share_weights_in_stack=False)
     | -- GenericBlock(units=1, thetas_dim=8, backcast_length=36, forecast_length=12, share_thetas=False) at @140604789377056
     | -- GenericBlock(units=1, thetas_dim=8, backcast_length=36, forecast_length=12, share_thetas=False) at @140604789375664
     | -- GenericBlock(units=1, thetas_dim=8, backcast_length=36, forecast_length=12, share_thetas=False) at @140604789375376


In [3]:
forecast = model.predict(predict_data=data36)

print(forecast)

data = pd.read_csv('infla-numpy-prev1.csv')
toRMSE = data[300:312]

print("dados originais")
print(toRMSE)
print(" --------- ")
print("dados do forecast")
print(forecast)
print("---####------#####------#####")
print(sqrt(mean_squared_error(toRMSE, forecast)))

import numpy as np
naiveDez1999 = np.array([1.35, 1.35, 1.35, 1.35, 1.35, 1.35, 1.35, 1.35, 1.35, 1.35, 1.35, 1.35])

print(sqrt(mean_squared_error(toRMSE, naiveDez1999)))

[[ 0.55798334]
 [ 0.540819  ]
 [-0.19978176]
 [ 0.54795545]
 [ 0.54299086]
 [-1.0424955 ]
 [ 0.55627304]
 [ 0.5543585 ]
 [ 0.67961335]
 [ 0.27148503]
 [ 0.5571451 ]
 [-0.5349204 ]]
dados originais
     ipca
300  0.25
301  0.86
302  0.93
303  0.31
304  0.83
305  0.53
306  0.96
307  0.87
308  1.16
309  1.25
310  0.95
311  0.73
 --------- 
dados do forecast
[[ 0.55798334]
 [ 0.540819  ]
 [-0.19978176]
 [ 0.54795545]
 [ 0.54299086]
 [-1.0424955 ]
 [ 0.55627304]
 [ 0.5543585 ]
 [ 0.67961335]
 [ 0.27148503]
 [ 0.5571451 ]
 [-0.5349204 ]]
---####------#####------#####
0.7794294199963512
0.6207455195166536
